from django.urls import path

from CFED import views

urlpatterns = [
    path('',views.login,name="login"),
    path('logincode', views.logincode, name="logincode"),
    path('Admin_home',views.Admin_home,name="Admin_home"),
    path('camera_info', views.camera_info, name="camera_info"),
    path('complaint', views.complaint, name="complaint"),
    path('reply/<int:id>', views.reply, name="reply"),
    path('View_feedback', views.View_feedback, name="View_feedback"),
    path('View_User', views.View_User, name="View_User"),
    path('reply_code', views.reply_code, name="reply_code"),
    path('ser_user', views.ser_user, name="ser_user"),
    path('ser_feed', views.ser_feed, name="ser_feed"),
    path('ser_cam', views.ser_cam, name="ser_cam"),
    path('ser_comp', views.ser_comp, name="ser_comp"),
    path('login_code', views.login_code, name="login_code"),
    path('register', views.register, name="register"),
    path('vcomplaints', views.vcomplaints, name="vcomplaints"),
    path('v_reply1', views.v_reply1, name="v_reply1"),
    path('v_notification', views.v_notification, name="v_notification"),
    path('vcamera', views.vcamera, name="vcamera"),
    path('deletecamera', views.deletecamera, name="deletecamera"),
    path('viewcamera', views.viewcamera, name="viewcamera"),
    path('acamera', views.acamera, name="acamera"),
    path('afeedback', views.afeedback, name="afeedback"),
    path('videosrc', views.videosrc, name="videosrc"),
    path('videosrc_search', views.videosrc_search, name="videosrc_search"),
    path('logout', views.logout, name="logout"),
    path('searchcomplaintvieww', views.searchcomplaintvieww, name="searchcomplaintvieww"),
    path('uservprofile', views.uservprofile, name="uservprofile"),
    path('insertEmotions', views.insertEmotions, name="insertEmotions"),
    path('viewemotion', views.viewemotion, name="viewemotion"),
    path('notificationv', views.notificationv, name="notificationv"),
    path('avgimag', views.avgimag, name="avgimag"),
    # path('videosrtec', views.videosrtec, name="videosrtec"),
]
